<?php

namespace IL\CoreBundle\Repository;

/**
 * SouscriptionMobileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SouscriptionMobileRepository extends \Doctrine\ORM\EntityRepository
{
    public function NumberOfSouscriptions()
    {
        $qb = $this->createQueryBuilder('u')
            ->select('count(u.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function getSouscriptionMobile($operateur, $statutLiaison, $dateDebut, $dateFin)
    {
        $dd1 = \DateTime::createFromFormat('d/m/Y', $dateDebut." 00:00:00");
        $dd2 = \DateTime::createFromFormat('d/m/Y', $dateFin." 23:59:59");


        if($operateur){
            $qb = $this->createQueryBuilder('s')
                ->andWhere('s.operateur = :operateur')
                ->andWhere('s.createdAt BETWEEN :dateDebut AND :dateFin')

                ->orderBy('s.createdAt', 'ASC')
                ->setParameters([
                    'operateur' => $operateur,
                    'dateDebut' => $dd1,
                    'dateFin' => $dd2
                ])
                ->getQuery();

            $result = $qb->execute();
            
           // dump($dd1); exit;

            return $result;
        }

    }
}
